name: Toolchain

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  toolchain:
    runs-on: ubuntu-latest
    container:
      image: koreader/kobase:0.4.0-22.04

    strategy:
      fail-fast: false
      matrix:
        tc: [kindle, kindle5, kindlepw2, kindlehf, kobo, kobov4, kobov5, nickel, remarkable, remarkable-aarch64, cervantes, pocketbook, bookeen]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y bison flex gawk gperf help2man libncurses-dev libtool-bin rsync texinfo

      - name: Generate toolchain
        run: ./gen-tc.sh ${{ matrix.tc }}

      - name: Tar artifacts
        run: tar -C ~ -czf ${{ matrix.tc }}.tar.gz x-tools

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tc }}
          path: ${{ matrix.tc }}.tar.gz
